#!/bin/bash

# Exit on any errors
set -e

# Creating config directory and copy example config file if it doesn't exists.
#if [ ! -d "~/.config/gfxbot" ]; then
#  echo Creating config directory.
#  mkdir -p ~/.config/gfxbot/
#fi

# Creating config file in bin directory.
if [ ! -f "$OPENSHIFT_REPO_DIR/bin/config.toml" ]; then
  cp $OPENSHIFT_REPO_DIR/conf/config.toml $OPENSHIFT_REPO_DIR/bin/config.toml
fi
