#!/bin/bash

# Exit on any errors
set -e

# Creating config directory and copy example config file if it doesn't exists.
#if [ ! -d "~/.config/gfxbot" ]; then
#  echo Creating config directory.
#  mkdir -p ~/.config/gfxbot/
#fi

# First, check if there's a config file in the data dir and copy it.
# If not, copy the config template.
if [ -f "$OPENSHIFT_DATA_DIR/config.toml" ]; then
  cp $OPENSHIFT_DATA_DIR/config.toml $OPENSHIFT_REPO_DIR/config.toml
elif [ ! -f "$OPENSHIFT_REPO_DIR/config.toml" ]; then
  cp $OPENSHIFT_REPO_DIR/conf/config.toml $OPENSHIFT_REPO_DIR/config.toml
fi
